POST http://localhost:3001/api/room/new HTTP/1.1
Content-Type: application/json

{}
###
POST http://localhost:3001/api/room/3857/player/new HTTP/1.1
Content-Type: application/json

{"name":"Alex"}
###
GET http://localhost:3001 HTTP/1.1
###
GET http://localhost:3001/api/room/3857 HTTP/1.1
###
GET http://localhost:3001/api/room/6449/start HTTP/1.1